[workspace]
resolver = "2"

members = [
    'node',
    'pallets/*',
    'runtime',
]

[profile.release]
panic = 'unwind'
rpath = false
debug = true
# incremental = true
# opt size:
# lto = "thin"
# opt-level = 's'
