version: "3.2"

services:
  pontem:
    container_name: pontem
    build:
      context: .build
      dockerfile: launch.Dockerfile
      args:
        PONTEM_VERSION: v0.5.1
        POLKADOT_VERSION: v0.9.18
        NODE_VERSION: 16
    ports:
      - "9944:9944" # Alice relaychain
      - "9946:9946" # Alice parachain
    volumes:
      - ./launch-config.json:/opt/pontem/launch-config.json
      - ./docker-launch:/opt/app
      # Uncomment if you are using the application from the source code
      # - ./target/release/pontem:/opt/pontem/target/release/pontem
      # - ./target/debug/pontem:/opt/pontem/target/release/pontem
