//! Autogenerated weights for sp_mvm
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2021-12-02, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:

// ./target/release/pontem

// benchmark

// --chain=dev

// --steps=50

// --repeat=20

// --pallet=sp-mvm

// --extrinsic=publish_module

// --execution=wasm

// --wasm-execution=compiled

// --heap-pages=4096

// --output=./pallets/sp-mvm/src/weights.rs

// --template=./template.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for sp_mvm.
pub trait WeightInfo {
	
	fn publish_module() -> Weight;
	
}

/// Weights for sp_mvm using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {

	
	
	// Storage: Mvm VMStorage (r:2 w:1)
	
	fn publish_module() -> Weight {
		(62_000_000 as Weight)
			
			
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			
			
			
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
			
			
	}
	
}

// For backwards compatibility and tests
impl WeightInfo for () {
	
	
	// Storage: Mvm VMStorage (r:2 w:1)
	
	fn publish_module() -> Weight {
		(62_000_000 as Weight)
			
			
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			
			
			
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
			
			
	}
	
}
