// Copyright 2020-2021 Pontem Foundation LTD.
// This file is part of Pontem Network.
// Apache 2.0

//! Autogenerated weights for groupsign
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-01-12, STEPS: `10`, REPEAT: 30, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 128

// Executed Command:
// ./target/release/pontem
// benchmark
// -ldebug
// --extrinsic
// *
// --pallet
// groupsign
// --steps=10
// --repeat=30
// --output=target/gs-bench
// --execution=wasm
// --template
// ./weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for groupsign.
pub trait WeightInfo {
        fn on_chain_message_check(a: u32, b: u32, c: u32, d: u32, ) -> Weight;
}

/// Weights for groupsign using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
        fn on_chain_message_check(a: u32, b: u32, c: u32, d: u32, ) -> Weight {
                (42_186_000 as Weight)
                        // Standard Error: 67_000
                        .saturating_add((1_690_000 as Weight).saturating_mul(a as Weight))
                        // Standard Error: 67_000
                        .saturating_add((911_000 as Weight).saturating_mul(b as Weight))
                        // Standard Error: 67_000
                        .saturating_add((440_000 as Weight).saturating_mul(c as Weight))
                        // Standard Error: 120_000
                        .saturating_add((9_652_000 as Weight).saturating_mul(d as Weight))
        }
}

// For backwards compatibility and tests
impl WeightInfo for () {
        fn on_chain_message_check(a: u32, b: u32, c: u32, d: u32, ) -> Weight {
                (42_186_000 as Weight)
                        // Standard Error: 67_000
                        .saturating_add((1_690_000 as Weight).saturating_mul(a as Weight))
                        // Standard Error: 67_000
                        .saturating_add((911_000 as Weight).saturating_mul(b as Weight))
                        // Standard Error: 67_000
                        .saturating_add((440_000 as Weight).saturating_mul(c as Weight))
                        // Standard Error: 120_000
                        .saturating_add((9_652_000 as Weight).saturating_mul(d as Weight))
        }
}
