// Copyright 2020-2021 Pontem Foundation LTD.
// This file is part of Pontem Network.
// Apache 2.0

//! Autogenerated weights for groupsign
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-01-11, STEPS: `1000`, REPEAT: 30, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 128

// Executed Command:
// ./target/release/pontem
// benchmark
// --extrinsic
// *
// --pallet
// groupsign
// -ldebug
// --steps=1000
// --repeat=30
// --output=target/gs-bench
// --execution=wasm
// --template
// ./weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for groupsign.
pub trait WeightInfo {
    fn on_chain_message_check_sr25519(s: u32, p: u32, ) -> Weight;
    fn on_chain_message_check_ed25519(s: u32, p: u32, ) -> Weight;
    fn on_chain_message_check_ecdsa(s: u32, p: u32, ) -> Weight;
}

/// Weights for groupsign using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
        fn on_chain_message_check_sr25519(s: u32, p: u32, ) -> Weight {
                (54_124_000 as Weight)
                        // Standard Error: 9_000
                        .saturating_add((649_000 as Weight).saturating_mul(s as Weight))
                        // Standard Error: 14_000
                        .saturating_add((505_000 as Weight).saturating_mul(p as Weight))
        }
        fn on_chain_message_check_ed25519(s: u32, p: u32, ) -> Weight {
                (51_636_000 as Weight)
                        // Standard Error: 6_000
                        .saturating_add((657_000 as Weight).saturating_mul(s as Weight))
                        // Standard Error: 10_000
                        .saturating_add((314_000 as Weight).saturating_mul(p as Weight))
        }
        fn on_chain_message_check_ecdsa(s: u32, p: u32, ) -> Weight {
                (157_960_000 as Weight)
                        // Standard Error: 7_000
                        .saturating_add((220_000 as Weight).saturating_mul(s as Weight))
                        // Standard Error: 12_000
                        .saturating_add((287_000 as Weight).saturating_mul(p as Weight))
        }
}

// For backwards compatibility and tests
impl WeightInfo for () {
        fn on_chain_message_check_sr25519(s: u32, p: u32, ) -> Weight {
                (54_124_000 as Weight)
                        // Standard Error: 9_000
                        .saturating_add((649_000 as Weight).saturating_mul(s as Weight))
                        // Standard Error: 14_000
                        .saturating_add((505_000 as Weight).saturating_mul(p as Weight))
        }
        fn on_chain_message_check_ed25519(s: u32, p: u32, ) -> Weight {
                (51_636_000 as Weight)
                        // Standard Error: 6_000
                        .saturating_add((657_000 as Weight).saturating_mul(s as Weight))
                        // Standard Error: 10_000
                        .saturating_add((314_000 as Weight).saturating_mul(p as Weight))
        }
        fn on_chain_message_check_ecdsa(s: u32, p: u32, ) -> Weight {
                (157_960_000 as Weight)
                        // Standard Error: 7_000
                        .saturating_add((220_000 as Weight).saturating_mul(s as Weight))
                        // Standard Error: 12_000
                        .saturating_add((287_000 as Weight).saturating_mul(p as Weight))
        }
}
